import "@/styles/globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WIKIROCKET",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-800 ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
